### ISSUE TITLE
F-Droid seems to believe "This application tracks and reports your activity to somewhere"

### ISSUE THREAD

**Issue by ciphergoth** [velazcod/Tinfoil-Facebook#54]
https://f-droid.org/repository/browse/?fdid=com.danvelazco.fbwrapper contains the above report. I'm guessing it's a false positive; if anyone knows why it's there it would be good to fix :)

**Comment by Foggalong** [comment]
They explain it i literally the line above :P you have to login into Facebook, and is what tracks your activity

**Comment by velazcod** [comment]
As @Foggalong said, it's explained right above, as well as [here](https://f-droid.org/wiki/page/Antifeature:Tracking), since it requires for you to log in to Facebook.

However, Tinfoil is running on a sandbox, so Facebook can't really do much with the information they get from you when using it, and location tracking is disabled by default.
